services:
  mysql_db:
    image: mysql:8.0
    container_name: bookstore_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bookstore_db
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 10

  atlas:
    image: arigaio/atlas:latest
    profiles: ["tools"]
    volumes:
      - .:/work
    working_dir: /work
    depends_on:
      mysql_db:
        condition: service_healthy
