// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bookstore-api/ent/book"
	"bookstore-api/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BookUpdate is the builder for updating Book entities.
type BookUpdate struct {
	config
	hooks    []Hook
	mutation *BookMutation
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdate) Where(ps ...predicate.Book) *BookUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *BookUpdate) SetTitle(v string) *BookUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdate) SetNillableTitle(v *string) *BookUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetIsbn sets the "isbn" field.
func (_u *BookUpdate) SetIsbn(v string) *BookUpdate {
	_u.mutation.SetIsbn(v)
	return _u
}

// SetNillableIsbn sets the "isbn" field if the given value is not nil.
func (_u *BookUpdate) SetNillableIsbn(v *string) *BookUpdate {
	if v != nil {
		_u.SetIsbn(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *BookUpdate) SetPrice(v float64) *BookUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *BookUpdate) SetNillablePrice(v *float64) *BookUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *BookUpdate) AddPrice(v float64) *BookUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetReleaseYear sets the "release_year" field.
func (_u *BookUpdate) SetReleaseYear(v int) *BookUpdate {
	_u.mutation.ResetReleaseYear()
	_u.mutation.SetReleaseYear(v)
	return _u
}

// SetNillableReleaseYear sets the "release_year" field if the given value is not nil.
func (_u *BookUpdate) SetNillableReleaseYear(v *int) *BookUpdate {
	if v != nil {
		_u.SetReleaseYear(*v)
	}
	return _u
}

// AddReleaseYear adds value to the "release_year" field.
func (_u *BookUpdate) AddReleaseYear(v int) *BookUpdate {
	_u.mutation.AddReleaseYear(v)
	return _u
}

// ClearReleaseYear clears the value of the "release_year" field.
func (_u *BookUpdate) ClearReleaseYear() *BookUpdate {
	_u.mutation.ClearReleaseYear()
	return _u
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdate) Mutation() *BookMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := book.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Book.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Isbn(); ok {
		if err := book.IsbnValidator(v); err != nil {
			return &ValidationError{Name: "isbn", err: fmt.Errorf(`ent: validator failed for field "Book.isbn": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Price(); ok {
		if err := book.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Book.price": %w`, err)}
		}
	}
	return nil
}

func (_u *BookUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Isbn(); ok {
		_spec.SetField(book.FieldIsbn, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(book.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(book.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReleaseYear(); ok {
		_spec.SetField(book.FieldReleaseYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReleaseYear(); ok {
		_spec.AddField(book.FieldReleaseYear, field.TypeInt, value)
	}
	if _u.mutation.ReleaseYearCleared() {
		_spec.ClearField(book.FieldReleaseYear, field.TypeInt)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookUpdateOne is the builder for updating a single Book entity.
type BookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookMutation
}

// SetTitle sets the "title" field.
func (_u *BookUpdateOne) SetTitle(v string) *BookUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableTitle(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetIsbn sets the "isbn" field.
func (_u *BookUpdateOne) SetIsbn(v string) *BookUpdateOne {
	_u.mutation.SetIsbn(v)
	return _u
}

// SetNillableIsbn sets the "isbn" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableIsbn(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetIsbn(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *BookUpdateOne) SetPrice(v float64) *BookUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillablePrice(v *float64) *BookUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *BookUpdateOne) AddPrice(v float64) *BookUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetReleaseYear sets the "release_year" field.
func (_u *BookUpdateOne) SetReleaseYear(v int) *BookUpdateOne {
	_u.mutation.ResetReleaseYear()
	_u.mutation.SetReleaseYear(v)
	return _u
}

// SetNillableReleaseYear sets the "release_year" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableReleaseYear(v *int) *BookUpdateOne {
	if v != nil {
		_u.SetReleaseYear(*v)
	}
	return _u
}

// AddReleaseYear adds value to the "release_year" field.
func (_u *BookUpdateOne) AddReleaseYear(v int) *BookUpdateOne {
	_u.mutation.AddReleaseYear(v)
	return _u
}

// ClearReleaseYear clears the value of the "release_year" field.
func (_u *BookUpdateOne) ClearReleaseYear() *BookUpdateOne {
	_u.mutation.ClearReleaseYear()
	return _u
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdateOne) Mutation() *BookMutation {
	return _u.mutation
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdateOne) Where(ps ...predicate.Book) *BookUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookUpdateOne) Select(field string, fields ...string) *BookUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Book entity.
func (_u *BookUpdateOne) Save(ctx context.Context) (*Book, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdateOne) SaveX(ctx context.Context) *Book {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := book.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Book.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Isbn(); ok {
		if err := book.IsbnValidator(v); err != nil {
			return &ValidationError{Name: "isbn", err: fmt.Errorf(`ent: validator failed for field "Book.isbn": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Price(); ok {
		if err := book.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Book.price": %w`, err)}
		}
	}
	return nil
}

func (_u *BookUpdateOne) sqlSave(ctx context.Context) (_node *Book, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Book.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, book.FieldID)
		for _, f := range fields {
			if !book.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != book.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Isbn(); ok {
		_spec.SetField(book.FieldIsbn, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(book.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(book.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReleaseYear(); ok {
		_spec.SetField(book.FieldReleaseYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReleaseYear(); ok {
		_spec.AddField(book.FieldReleaseYear, field.TypeInt, value)
	}
	if _u.mutation.ReleaseYearCleared() {
		_spec.ClearField(book.FieldReleaseYear, field.TypeInt)
	}
	_node = &Book{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
