// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bookstore-api/ent/book"
	"bookstore-api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookFields := schema.Book{}.Fields()
	_ = bookFields
	// bookDescTitle is the schema descriptor for title field.
	bookDescTitle := bookFields[1].Descriptor()
	// book.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	book.TitleValidator = func() func(string) error {
		validators := bookDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// bookDescIsbn is the schema descriptor for isbn field.
	bookDescIsbn := bookFields[2].Descriptor()
	// book.IsbnValidator is a validator for the "isbn" field. It is called by the builders before save.
	book.IsbnValidator = func() func(string) error {
		validators := bookDescIsbn.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(isbn string) error {
			for _, fn := range fns {
				if err := fn(isbn); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// bookDescPrice is the schema descriptor for price field.
	bookDescPrice := bookFields[3].Descriptor()
	// book.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	book.PriceValidator = bookDescPrice.Validators[0].(func(float64) error)
	// bookDescCreatedAt is the schema descriptor for created_at field.
	bookDescCreatedAt := bookFields[4].Descriptor()
	// book.DefaultCreatedAt holds the default value on creation for the created_at field.
	book.DefaultCreatedAt = bookDescCreatedAt.Default.(func() int64)
	// bookDescReleaseYear is the schema descriptor for release_year field.
	bookDescReleaseYear := bookFields[5].Descriptor()
	// book.ReleaseYearValidator is a validator for the "release_year" field. It is called by the builders before save.
	book.ReleaseYearValidator = bookDescReleaseYear.Validators[0].(func(int) error)
	// bookDescID is the schema descriptor for id field.
	bookDescID := bookFields[0].Descriptor()
	// book.IDValidator is a validator for the "id" field. It is called by the builders before save.
	book.IDValidator = bookDescID.Validators[0].(func(uint32) error)
}
